version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: delivery_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: delivery_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - delivery_network

volumes:
  postgres_data:
    driver: local

networks:
  delivery_network:
    driver: bridge
